export const portfolio = [
  {
    title: 'Технокряк',
    type: 'Веб-сайт',
    tags: ['Веб-сайты', 'Все'],
    mobile1x: './images/project-1-mobile.jpg',
    mobile2x: './images/project-1-mobile@2x.jpg',
    mobile3x: './images/project-1-mobile@3x.jpg',
    tablet1x: './images/project-1-tablet.jpg',
    tablet2x: './images/project-1-tablet@2x.jpg',
    tablet3x: './images/project-1-tablet@3x.jpg',
    desktop1x: './images/project-1-desktop.jpg',
    desktop2x: './images/project-1-desktop@2x.jpg',
    desktop3x: './images/project-1-desktop@3x.jpg',
    desc: 'Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения о компании или частном лице.',
    alt: 'Картинка проекта Технокряк',
  },
  {
    title: 'Постер New Orlean vs Golden Star',
    type: 'Дизайн',
    tags: ['Дизайн', 'Все'],
    mobile1x: './images/project-2-mobile.jpg',
    mobile2x: './images/project-2-mobile@2x.jpg',
    mobile3x: './images/project-2-mobile@3x.jpg',
    tablet1x: './images/project-2-tablet.jpg',
    tablet2x: './images/project-2-tablet@2x.jpg',
    tablet3x: './images/project-2-tablet@3x.jpg',
    desktop1x: './images/project-2-desktop.jpg',
    desktop2x: './images/project-2-desktop@2x.jpg',
    desktop3x: './images/project-2-desktop@3x.jpg',
    desc: 'Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения о компании или частном лице.',
    alt: 'Картинка проекта Постер New Orlean vs Golden Star',
  },
  {
    title: 'Ресторан Seafood',
    type: 'Приложение',
    tags: ['Приложения', 'Все'],
    mobile1x: './images/project-3-mobile.jpg',
    mobile2x: './images/project-3-mobile@2x.jpg',
    mobile3x: './images/project-3-mobile@3x.jpg',
    tablet1x: './images/project-3-tablet.jpg',
    tablet2x: './images/project-3-tablet@2x.jpg',
    tablet3x: './images/project-3-tablet@3x.jpg',
    desktop1x: './images/project-3-desktop.jpg',
    desktop2x: './images/project-3-desktop@2x.jpg',
    desktop3x: './images/project-3-desktop@3x.jpg',
    desc: 'Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения о компании или частном лице.',
    alt: 'Картинка проекта Ресторан Seafood',
  },
  {
    title: 'Проект Prime',
    type: 'Маркетинг',
    tags: ['Маркетинг', 'Все'],
    mobile1x: './images/project-4-mobile.jpg',
    mobile2x: './images/project-4-mobile@2x.jpg',
    mobile3x: './images/project-4-mobile@3x.jpg',
    tablet1x: './images/project-4-tablet.jpg',
    tablet2x: './images/project-4-tablet@2x.jpg',
    tablet3x: './images/project-4-tablet@3x.jpg',
    desktop1x: './images/project-4-desktop.jpg',
    desktop2x: './images/project-4-desktop@2x.jpg',
    desktop3x: './images/project-4-desktop@3x.jpg',
    desc: 'Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения о компании или частном лице.',
    alt: 'Картинка проекта Проект Prime',
  },
  {
    title: 'Проект Boxes',
    type: 'Приложение',
    tags: ['Приложения', 'Все'],
    mobile1x: './images/project-5-mobile.jpg',
    mobile2x: './images/project-5-mobile@2x.jpg',
    mobile3x: './images/project-5-mobile@3x.jpg',
    tablet1x: './images/project-5-tablet.jpg',
    tablet2x: './images/project-5-tablet@2x.jpg',
    tablet3x: './images/project-5-tablet@3x.jpg',
    desktop1x: './images/project-5-desktop.jpg',
    desktop2x: './images/project-5-desktop@2x.jpg',
    desktop3x: './images/project-5-desktop@3x.jpg',
    desc: 'Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения о компании или частном лице.',
    alt: 'Картинка проекта Проект Boxes',
  },
  {
    title: 'Inspiration has no Borders',
    type: 'Веб-сайт',
    tags: ['Веб-сайты', 'Все'],
    mobile1x: './images/project-6-mobile.jpg',
    mobile2x: './images/project-6-mobile@2x.jpg',
    mobile3x: './images/project-6-mobile@3x.jpg',
    tablet1x: './images/project-6-tablet.jpg',
    tablet2x: './images/project-6-tablet@2x.jpg',
    tablet3x: './images/project-6-tablet@3x.jpg',
    desktop1x: './images/project-6-desktop.jpg',
    desktop2x: './images/project-6-desktop@2x.jpg',
    desktop3x: './images/project-6-desktop@3x.jpg',
    desc: 'Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения о компании или частном лице.',
    alt: 'Картинка проекта Inspiration has no Borders',
  },
  {
    title: 'Издание Limited Edition',
    type: 'Дизайн',
    tags: ['Дизайн', 'Все'],
    mobile1x: './images/project-7-mobile.jpg',
    mobile2x: './images/project-7-mobile@2x.jpg',
    mobile3x: './images/project-7-mobile@3x.jpg',
    tablet1x: './images/project-7-tablet.jpg',
    tablet2x: './images/project-7-tablet@2x.jpg',
    tablet3x: './images/project-7-tablet@3x.jpg',
    desktop1x: './images/project-7-desktop.jpg',
    desktop2x: './images/project-7-desktop@2x.jpg',
    desktop3x: './images/project-7-desktop@3x.jpg',
    desc: 'Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения о компании или частном лице.',
    alt: 'Картинка проекта Издание Limited Edition',
  },
  {
    title: 'Проект LAB',
    type: 'Маркетинг',
    tags: ['Маркетинг', 'Все'],
    mobile1x: './images/project-8-mobile.jpg',
    mobile2x: './images/project-8-mobile@2x.jpg',
    mobile3x: './images/project-8-mobile@3x.jpg',
    tablet1x: './images/project-8-tablet.jpg',
    tablet2x: './images/project-8-tablet@2x.jpg',
    tablet3x: './images/project-8-tablet@3x.jpg',
    desktop1x: './images/project-8-desktop.jpg',
    desktop2x: './images/project-8-desktop@2x.jpg',
    desktop3x: './images/project-8-desktop@3x.jpg',
    desc: 'Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения о компании или частном лице.',
    alt: 'Картинка проекта Проект LAB',
  },
  {
    title: 'Growing Business',
    type: 'Приложение',
    tags: ['Приложения', 'Все'],
    mobile1x: './images/project-9-mobile.jpg',
    mobile2x: './images/project-9-mobile@2x.jpg',
    mobile3x: './images/project-9-mobile@3x.jpg',
    tablet1x: './images/project-9-tablet.jpg',
    tablet2x: './images/project-9-tablet@2x.jpg',
    tablet3x: './images/project-9-tablet@3x.jpg',
    desktop1x: './images/project-9-desktop.jpg',
    desktop2x: './images/project-9-desktop@2x.jpg',
    desktop3x: './images/project-9-desktop@3x.jpg',
    desc: 'Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения о компании или частном лице.',
    alt: 'Картинка проекта Growing Business',
  },
];
